### ISSUE TITLE
Panic in tokenizer Expected ":", but parsed "+"

### ISSUE THREAD

**Issue by xypron** [codyd51/uefirc#1]
`JOIN #zzzz13`

resulted in 

```
[PANIC]: panicked at src/irc/tokenizer.rs:81:13:
Expected ":", but parsed "+"
```

using what is in the release file.

**Comment by codyd51** [comment]
Hi, thank you very much for the clear and reproducible bug report!

Thanks as well for giving this app a try 🙂.

The issue here was that I was assuming IRC messages always have a leading colon at the start of the trailing message, like so:

`:coulomb.oftc.net MODE #zzzz13 :+nt`

As it turns out, the leading colon is optional based on whether it's necessary to disambiguate the message, so the server can send this instead:

`:coulomb.oftc.net MODE #zzzz13 +nt`

I've fixed this in 5110b04, and have uploaded a release for `v1.0.1` [here](https://github.com/codyd51/uefirc/releases/tag/1.0.1)
